spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://app_db:5432/appointment_db
    username: postgres
    password: app
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
